name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ros:rolling
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@tier4/proposal

      - name: Build and test
        uses: autowarefoundation/autoware-github-actions/colcon-build-and-test@tier4/proposal
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: build_depends.repos

      - name: Check the existence of coverage files
        id: check-file-existence
        uses: autowarefoundation/autoware-github-actions/check-file-existence@tier4/proposal
        with:
          files: |
            lcov/total_coverage.info
            coveragepy/.coverage
          condition: or

      - name: Upload coverage to CodeCov
        if: ${{ steps.check-file-existence.outputs.exists == 'true' }}
        uses: codecov/codecov-action@v2
        with:
          files: lcov/total_coverage.info,coveragepy/.coverage
          fail_ci_if_error: false
          verbose: true
