name: Build and test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: osrf/ros:galactic-desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone dependency packages
        run: |
          apt-get -y update
          rosdep update
          rosdep install -y --from-paths . --ignore-src --rosdistro galactic

      - name: Build
        run: |
          . /opt/ros/galactic/setup.bash
          colcon build --event-handlers console_cohesion+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Run tests
        run: |
          . /opt/ros/galactic/setup.bash
          colcon test --event-handlers console_cohesion+ \
            --return-code-on-test-failure
